entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"
service:
  type: LoadBalancer
  spec:
    ports:
      - name: web
        port: 80
        targetPort: 80
        protocol: TCP
      - name: websecure
        port: 443
        targetPort: 443
        protocol: TCP
providers:
  kubernetesCRD:
    enabled: true
  kubernetesIngress:
    enabled: true